import pandas as pd
from ydata_profiling import ProfileReport
#part1
#loading data
data = pd.read_csv('Tunisair_flights_dataset.csv')
df=pd.DataFrame(data)
#exploring data
print(df.info())
print(df.head())
#looking for missing values
missing_values=df.isnull().sum()
print(f'\nmissing values in each columns:\n{missing_values[missing_values!=0]}')
#get summary statistics for the numerical columns in the dataset
print('summary_statistic\n',df.describe())
#part2
#Use ydata-profiling to generate a report of the provided dataset
profile= ProfileReport(df,title='Tunisair Data Profiling Report', explorative= True)
profile.to_file('Tunisair_Data_Exploration.html')
#Look for missing values in the dataset. You can use the report generated by ydata-profiling to identify missing values.
#there is no missing values

#Look for correlations between different columns in the dataset. You can use the report generated by ydata-profiling to identify correlations between different columns.
